import { createContext, useContext, useEffect, useState } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  toggleLanguage: () => {},
  t: (key) => key,
});

const translations: Record<Language, Record<string, string>> = {
  en: {
    portalTitle: 'ASU Medical Portal',
    asu: 'Ain Shams University',
    selectYear: 'Select Academic Year',
    selectYearDesc: '"And whoever saves one - it is as if he had saved mankind entirely." — Quran [5:32]',
    year1: 'Year 1',
    year2: 'Year 2',
    year3: 'Year 3',
    year4: 'Year 4',
    year5: 'Year 5',
    year6: 'Year 6',
    preClerkship: 'Pre-Clerkship Phase',
    clerkship: 'Clinical Clerkship Phase',
    enter: 'Enter',
    empPortal: 'EMP',
    mainstreamPortal: 'Mainstream',
    umsPortal: 'UMS',
    syllabusTracker: 'Study Progress Tracker',
    resumeHistory: 'Resume From History',
    selectSemester: 'Select Semester',
    selectSemesterDesc: 'Choose the semester you want to study.',
    semester1: 'Semester 1',
    semester2: 'Semester 2',
    creditPoints: 'Credit Points',
    back: 'Back',
    selectModule: 'Select Syllabus Module',
    selectModuleDesc: 'Choose a module to begin studying.',
    activeModules: 'Active Modules',
    lockedModules: 'Coming Soon Modules',
    questions: 'Questions',
    mcqs: 'MCQs',
    essays: 'Essays',
    marks: 'Marks',
    cp: 'CP',
    selectMode: 'Select Study Mode',
    selectModeDesc: 'Pick the format that fits your learning goal for this module.',
    mcqPractice: 'MCQ Practice',
    mcqPracticeDesc: 'Traditional multiple-choice questions with instant feedback and explanations.',
    essayStudy: 'Written Study',
    essayStudyDesc: 'Written clinical essays, short answers, and structured cases with self-grading.',
    mixedExam: 'Mixed Exam',
    mixedExamDesc: 'A simulated, timed exam combining both MCQs and Essays for maximum preparation.',
    startMode: 'Start Mode',
    selectChapter: 'Select a Chapter',
    selectChapterDesc: 'Browse textbook chapters, view details, and start a custom test.',
    quickStartAll: 'Quick Start (All Chapters)',
    quickStartAllDesc: 'Start studying all topics in this chapter combined.',
    page: 'Page',
    selectSubject: 'Select Subject Topic',
    selectSubjectDesc: 'Choose a specific subject to study, or test yourself on the whole chapter.',
    quickStartAllSubjects: 'Quick Start (All Subjects)',
    quickStartAllSubjectsDesc: 'Practice all questions from all subjects in this chapter.',
    question: 'Question',
    of: 'of',
    timeElapsed: 'Time Elapsed',
    flagQuestion: 'Flag Question',
    flagged: 'Flagged',
    checkAnswer: 'Check Answer',
    nextQuestion: 'Next Question',
    submitExam: 'Submit Exam',
    confirmFinishTitle: 'Finish Quiz?',
    confirmFinishDesc: 'Are you sure you want to finish the quiz and view results?',
    yesFinish: 'Yes, Finish',
    cancel: 'Cancel',
    yourAnswer: 'Your Answer',
    modelAnswer: 'Model Answer',
    explanation: 'Explanation',
    keyConcept: 'Key Concept',
    howDidYouDo: 'How did you do?',
    correct: 'Correct',
    incorrect: 'Incorrect',
    selfGradingRequired: 'Self-Grading Required',
    performanceDashboard: 'Performance Dashboard',
    examResults: 'Exam Results',
    greatWork: 'Great work!',
    studyHarder: 'Study harder!',
    score: 'Score',
    correctAnswers: 'Correct Answers',
    totalQuestions: 'Total Questions',
    timeSpent: 'Time Spent',
    accuracyRate: 'Accuracy Rate',
    allQuestions: 'All Questions',
    incorrectOnly: 'Incorrect Only',
    flaggedOnly: 'Flagged Only',
    reviewQuestions: 'Review Questions',
    restartQuiz: 'Restart Quiz',
    exitPortal: 'Exit to Portal',
    clearHistory: 'Clear History',
    comingSoon: 'Coming Soon...',
    dbPending: 'Database Integration Pending',
    dbPendingDesc: 'The database for this module is currently being prepared and will be launched in the next update.',
    tryEndocrine: 'Try Endocrine Module',
    close: 'Close',
    portal: 'Portal',
    
    // Additional keys
    backToStudyModes: 'Back to Study Modes',
    subjectsCount: 'subjects',
    recentResults: 'Recent Results',
    sessions: 'sessions',
    clear: 'Clear',
    subjectColorGuide: 'Subject Color Guide',
    backToSubjects: 'Back to Subjects',
    availableSubjects: 'Subjects Available',
    chooseSubject: 'Choose Your Subject',
    quickStartAllSubjectsBanner: 'Quick Start — All Subjects',
    quickStartAllSubjectsDescBanner: 'Randomized mix of all questions from every subject',
    startAll: 'Start All',
    begin: 'Begin',
    sessionProgress: 'Session Progress',
    correctPoints: 'Correct Points',
    remaining: 'Remaining',
    questionMap: 'Question Map',
    wrong: 'Wrong',
    current: 'Current',
    retakeQuiz: 'Retake Quiz',
    tryAnotherSubject: 'Try Another Subject',
    backToChapters: 'Back to Chapters',
    developedForStudents: 'Developed for medical students. For inquiries, database updates, or error reports, please contact: ',
    chaptersCount: 'Chapters',
    subjectsTab: 'Subjects',
    finish: 'Finish',
    confirmFinish: 'Are you sure you want to finish the quiz?',
    start: 'Start',
    chapter: 'Chapter',
    clinicalCase: 'Clinical Case',
    fillBlank: 'Fill in the Blank',
    multipleChoice: 'Multiple Choice',
    trueFalse: 'True / False',
    essayPlaceholder: 'Type your answer here (optional). If solving in your head, just click \'Reveal Model Answer\' below to grade yourself...',
    revealModelAnswer: 'Reveal Model Answer',
    modelAnswerReference: 'Model Answer Reference',
    selfGrading: 'Self-grading',
    selfGradingDesc: 'Select how close your notes were to the model answer:',
    personalNotes: 'Personal Notes',
  },
  ar: {
    portalTitle: 'البوابة الطبية لجامعة عين شمس',
    asu: 'جامعة عين شمس',
    selectYear: 'اختر السنة الدراسية',
    selectYearDesc: '﴿وَمَنْ أَحْيَاهَا فَكَأَنَّمَا أَحْيَا النَّاسَ جَمِيعًا﴾ — سورة المائدة [٥:٣٢]',
    year1: 'السنة الأولى',
    year2: 'السنة الثانية',
    year3: 'السنة الثالثة',
    year4: 'السنة الرابعة',
    year5: 'السنة الخامسة',
    year6: 'السنة السادسة',
    preClerkship: 'مرحلة ما قبل التدريب الإكلينيكي',
    clerkship: 'مرحلة التدريب الإكلينيكي',
    enter: 'دخول',
    empPortal: 'EMP',
    mainstreamPortal: 'البرنامج العام',
    umsPortal: 'UMS',
    syllabusTracker: 'متابع دراسي',
    resumeHistory: 'الاستمرار من المحاولات السابقة',
    selectSemester: 'اختر الفصل الدراسي',
    selectSemesterDesc: 'اختر الفصل الدراسي الذي تريد دراسته.',
    semester1: 'الفصل الدراسي الأول',
    semester2: 'الفصل الدراسي الثاني',
    creditPoints: 'النقاط المعتمدة',
    back: 'رجوع',
    selectModule: 'اختر وحدة المنهج',
    selectModuleDesc: 'اختر وحدة لبدء المذاكرة.',
    activeModules: 'الوحدات النشطة',
    lockedModules: 'الوحدات القادمة قريبًا',
    questions: 'أسئلة',
    mcqs: 'الاختيار من متعدد',
    essays: 'أسئلة مقالية',
    marks: 'درجة',
    cp: 'ساعة معتمدة',
    selectMode: 'اختر وضع الدراسة',
    selectModeDesc: 'اختر التنسيق الذي يناسب هدفك التعليمي لهذه الوحدة.',
    mcqPractice: 'تدريب الاختيار من متعدد',
    mcqPracticeDesc: 'أسئلة اختيار من متعدد تقليدية مع تقييم فوري وشروحات تفصيلية.',
    essayStudy: 'دراسة الأسئلة المقالية',
    essayStudyDesc: 'أسئلة مقالية إكلينيكية مكتوبة، إجابات قصيرة، وحالات منظمة مع تقييم ذاتي.',
    mixedExam: 'امتحان مختلط',
    mixedExamDesc: 'امتحان محاكي وموقوت يجمع بين أسئلة الاختيار من متعدد والمقالية لأقصى درجات الاستعداد.',
    startMode: 'ابدأ الوضع',
    selectChapter: 'اختر فصل الدراسة',
    selectChapterDesc: 'تصفح فصول الكتاب الدراسي، واطلع على التفاصيل، وابدأ اختبارًا مخصصًا.',
    quickStartAll: 'بدء سريع (كل الفصول)',
    quickStartAllDesc: 'ابدأ مذاكرة جميع المواضيع في هذا الفصل معًا.',
    page: 'صفحة',
    selectSubject: 'اختر موضوع الدرس',
    selectSubjectDesc: 'اختر موضوعًا معينًا للدراسة، أو اختبر نفسك في الفصل بأكمله.',
    quickStartAllSubjects: 'بدء سريع (كل المواضيع)',
    quickStartAllSubjectsDesc: 'تدرب على جميع الأسئلة من جميع المواضيع في هذا الفصل.',
    question: 'السؤال',
    of: 'من',
    timeElapsed: 'الوقت المنقضي',
    flagQuestion: 'تحديد السؤال',
    flagged: 'محدد',
    checkAnswer: 'التحقق من الإجابة',
    nextQuestion: 'السؤال التالي',
    submitExam: 'تسليم الامتحان',
    confirmFinishTitle: 'إنهاء الاختبار؟',
    confirmFinishDesc: 'هل أنت متأكد من رغبتك في إنهاء الاختبار وعرض النتائج؟',
    yesFinish: 'نعم، إنهاء',
    cancel: 'إلغاء',
    yourAnswer: 'إجابتك',
    modelAnswer: 'الإجابة النموذجية',
    explanation: 'الشرح',
    keyConcept: 'المفهوم الأساسي',
    howDidYouDo: 'كيف كان أداؤك؟',
    correct: 'صحيح',
    incorrect: 'غير صحيح',
    selfGradingRequired: 'مطلوب تقييم ذاتي',
    performanceDashboard: 'لوحة تحكم الأداء',
    examResults: 'نتائج الامتحان',
    greatWork: 'عمل رائع!',
    studyHarder: 'اجتهد أكثر!',
    score: 'النتيجة',
    correctAnswers: 'الإجابات الصحيحة',
    totalQuestions: 'إجمالي الأسئلة',
    timeSpent: 'الوقت المستغرق',
    accuracyRate: 'معدل الدقة',
    allQuestions: 'كل الأسئلة',
    incorrectOnly: 'غير الصحيحة فقط',
    flaggedOnly: 'المحددة فقط',
    reviewQuestions: 'مراجعة الأسئلة',
    restartQuiz: 'إعادة الاختبار',
    exitPortal: 'الخروج للبوابة',
    clearHistory: 'مسح السجل',
    comingSoon: 'قريباً...',
    dbPending: 'قيد دمج قاعدة البيانات',
    dbPendingDesc: 'قاعدة بيانات هذه الوحدة قيد التحضير حاليًا وسيتم إطلاقها في التحديث القادم.',
    tryEndocrine: 'جرب وحدة الغدد الصماء',
    close: 'إغلاق',
    portal: 'البوابة',
    
    // Additional keys
    backToStudyModes: 'الرجوع لأوضاع الدراسة',
    subjectsCount: 'مواد',
    recentResults: 'النتائج الأخيرة',
    sessions: 'جلسات',
    clear: 'مسح',
    subjectColorGuide: 'دليل ألوان المواد',
    backToSubjects: 'الرجوع للمواد',
    availableSubjects: 'مواد متاحة',
    chooseSubject: 'اختر المادة',
    quickStartAllSubjectsBanner: 'بدء سريع — جميع المواد',
    quickStartAllSubjectsDescBanner: 'مزيج عشوائي من جميع الأسئلة من كل مادة',
    startAll: 'بدء الكل',
    begin: 'بدء',
    sessionProgress: 'تقدم الجلسة',
    correctPoints: 'النقاط الصحيحة',
    remaining: 'المتبقي',
    questionMap: 'خريطة الأسئلة',
    wrong: 'خطأ',
    current: 'الحالي',
    retakeQuiz: 'إعادة الاختبار',
    tryAnotherSubject: 'جرب مادة أخرى',
    backToChapters: 'الرجوع للفصول',
    developedForStudents: 'تم تطويره لطلاب الطب. للاستفسارات، تحديثات قاعدة البيانات، أو تقارير الأخطاء، يرجى الاتصال بـ: ',
    chaptersCount: 'الفصول',
    subjectsTab: 'المواد',
    finish: 'إنهاء',
    confirmFinish: 'هل أنت متأكد من رغبتك في إنهاء الاختبار؟',
    start: 'بدء',
    chapter: 'الفصل',
    clinicalCase: 'الحالة الإكلينيكية',
    fillBlank: 'أكمل الفراغ',
    multipleChoice: 'الاختيار من متعدد',
    trueFalse: 'صح / خطأ',
    essayPlaceholder: 'اكتب إجابتك هنا (اختياري). إذا كنت تحل في ذهنك، فقط اضغط على "عرض الإجابة النموذجية" بالأسفل لتقييم نفسك...',
    revealModelAnswer: 'عرض الإجابة النموذجية',
    modelAnswerReference: 'مرجع الإجابة النموذجية',
    selfGrading: 'التقييم الذاتي',
    selfGradingDesc: 'حدد مدى قرب ملاحظاتك من الإجابة النموذجية:',
    personalNotes: 'ملاحظات شخصية',
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    try {
      const pref = localStorage.getItem('language');
      return pref === 'ar' ? 'ar' : 'en';
    } catch {
      return 'en';
    }
  });

  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
    try {
      localStorage.setItem('language', language);
    } catch (e) {
      console.error(e);
    }
  }, [language]);

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'en' ? 'ar' : 'en'));
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
