import json,hashlib,pathlib
root=pathlib.Path(__file__).parent
b=json.loads((root/'snapshot-IAE-1.json').read_text());ql=[q for c in b['chapters'] for s in c['subjects'] for q in s['questions']];qs={q['id']:q for q in ql};rows={}
def add(n,changes,reason,url=None,locator='',claim='',exclude=False):
 id=f'IAE-1-SRC-{n:04d}';q=qs[id];rows[id]={'module':'IAE-1','id':id,'question_hash':hashlib.sha256(json.dumps(q,sort_keys=True,ensure_ascii=False).encode()).hexdigest(),'decision':'exclude' if exclude else 'correct','changes':changes,'reason':reason,'evidence':[{'url':url,'locator':locator,'claim':claim,'opened_full_text':True}] if url else []}
def ex(n,r,url=None,locator='',claim=''):add(n,{},r,url,locator,claim,True)
tongue='https://www.ncbi.nlm.nih.gov/books/NBK549823/?report=printable'
thorax='https://openstax.org/books/anatomy-and-physiology-2e/pages/7-4-the-thoracic-cage'
pelvis='https://openstax.org/books/anatomy-and-physiology-2e/pages/8-3-the-pelvic-girdle-and-pelvis'
add(26,{'explanation':'The second scalp layer is dense connective tissue containing the main vessels and nerves. Occipitofrontalis and its epicranial aponeurosis form the third, musculoaponeurotic layer.'},'The explanation incorrectly places scalp muscles in the second layer.')
ex(29,'The temporalis tendon and lower portion of the muscle enter the infratemporal fossa; all listed structures are associated with the fossa, so treating temporalis as wholly absent is ambiguous.')
add(56,{'text':'Which nerve supplies all intrinsic tongue muscles and most extrinsic tongue muscles, with palatoglossus as the exception?','explanation':'The hypoglossal nerve supplies all intrinsic tongue muscles and most extrinsic muscles. Palatoglossus is supplied by the vagus nerve through the pharyngeal plexus.'},'The broad original wording permits vagus as well as hypoglossal; explanation falsely denied vagal tongue motor supply.',tongue,'Nerves','Palatoglossus is a tongue muscle supplied by vagus; other tongue muscles are hypoglossal-supplied.')
add(57,{'text':'Which of the following nerves supplies the muscles of facial expression?'},'Facial muscles broadly includes muscles of mastication; restrict the intended none-of-the-above answer to expression.')
ex(70,'Maxilla is both irregular by shape and pneumatic by its air-containing sinus; the classifications in the alternatives are not mutually exclusive.')
add(80,{'text':'The ___ nerve provides motor supply to all intrinsic and most extrinsic tongue muscles, except palatoglossus.'},'Qualifies tongue motor supply to avoid the vagal palatoglossus exception.',tongue,'Nerves','Palatoglossus is vagal-supplied, unlike the other tongue muscles.')
q=qs['IAE-1-SRC-0087'];pairs=json.loads(json.dumps(q['pairs']));
for p in pairs:
 if 'decuss' in p['premise'].lower():p['target']='Crossing of tract fibers across the midline.'
add(87,{'pairs':pairs,'explanation':'A decussation is the crossing of nerve fibers across the midline and may involve either ascending or descending pathways. The other pairs describe their listed nervous-system structures.'},'Decussation is not limited to descending tracts.')
ex(92,'Claim that pineal inhibition of many endocrine activities distinguishes it from hypothalamus is an unqualified historical generalization; retain only after course-source adjudication.')
ex(104,'Vagus supplies taste from the epiglottic region and motor innervation to palatoglossus, so the options allow more than one tongue function.',tongue,'Nerves','Palatoglossus has vagal motor innervation.')
add(118,{'text':'Which of the following tissues lacks conventional lymphatic vessels within its parenchyma?','explanation':'Brain parenchyma lacks conventional lymphatic vessels. This does not mean that the entire cranial compartment lacks lymphatic drainage: meningeal lymphatic vessels are present.'},'Distinguishes brain parenchyma from meningeal lymphatic vessels.')
add(143,{'text':'Which ribs attach to the sternum indirectly through the costal cartilage of the rib above?','explanation':'Ribs 8–10 attach indirectly through adjoining costal cartilage. Ribs 11–12 are floating ribs without an anterior sternal connection; the broader false-rib category includes ribs 8–12.'},'The false-rib category can include floating ribs; define the intended indirect-attachment subset explicitly.',thorax,'Rib Classifications','8–10 attach via adjoining cartilage; 11–12 float; 8–12 lack direct sternal attachment.')
ex(152,'Both the intermediate position of internal intercostals and the localization of innermost intercostals to the intercostal spaces are true as written.')
add(154,{'text':'A typical intercostal space among the upper nine contains all the following EXCEPT:'},'The lower two intercostal spaces lack anterior intercostal arteries; original each-space generalization was false.')
add(183,{'text':'In the usual right-dominant coronary circulation, the posterior interventricular artery is a branch of which artery?'},'Coronary dominance varies; in left dominance the circumflex gives this branch.')
add(190,{'text':'The manubriosternal joint is classified as:'},'The sternum also has a primary cartilaginous xiphisternal joint; original all-parts wording was false.')
add(207,{'text':'The true ribs are ___ pairs in number, while the floating ribs are ___ pairs in number.'},'Answer values 7 and 2 count pairs, not individual ribs.',thorax,'Rib Classifications','There are seven pairs of true ribs and two pairs of floating ribs.')
add(214,{'text':'Which structure lies immediately deep to the transversus abdominis muscle?'},'Parietal peritoneum and extraperitoneal fat also lie deep to the muscle; immediately makes the intended fascia answer unique.')
ex(218,'The muscle lies deep to external oblique as well as having an arch above the round ligament; the explanation wrongly rejects the former because it also lies deep to internal oblique.')
ex(233,'The phrenic nerve supplies the diaphragm including sensory supply to the central upper surface; C and D are both true as written.')
ex(232,'The duodenojejunal junction is conventionally near L2 rather than the L1 transpyloric plane; alongside the 7th cartilage, it produces a second EXCEPT option.')
ex(270,'The organs named are not wholly restricted to one side of the subcostal plane, and small intestine includes duodenum; the broad location wording is unreliable.')
ex(285,'The pancreas includes head, body and tail as well as a neck. The option says includes, not consists only of, so A and E are both true.')
ex(286,'Kidney levels vary by side and individual; a right renal hilum near L2 is not categorically incorrect. The unqualified single-answer item is unreliable.')
ex(305,'Beginning of jejunum/duodenojejunal junction is near L2, below the L1 transpyloric plane, so it is also a defensible NOT option alongside right colic flexure.')
ex(327,'Two unrestricted blanks naming any two alimentary-tract parts admit many valid answers; exact pharynx/oesophagus key is not uniquely determined.')
add(338,{'explanation':'The ischial spine separates the greater and lesser sciatic notches. The iliac crest is the upper border of the ilium, and the pubis has two rami. The obturator foramen is bounded by both pubis and ischium, rather than by either bone alone.'},'The previous explanation falsely states that only pubic rami enclose the obturator foramen.',pelvis,'Pelvis','Obturator foramen lies between pubis and ischium.')
add(342,{'text':'Which listed articulation includes an intervertebral-body symphysis, a secondary cartilaginous joint?'},'Lumbosacral region also includes synovial facet joints; specifies the intended disc articulation.')
ex(344,'The bony true pelvis is conventionally bounded by inlet and outlet, while the functional cavity terminates at pelvic floor; both D and E depend on the stated boundary convention.',pelvis,'Pelvis','Pelvic inlet is superior margin and pelvic outlet inferior limit of lesser pelvic cavity.')

add(351,{'explanation':'The sympathetic trunk is a chain of autonomic paravertebral ganglia. The other listed nerves have no ganglia along the specified pelvic course. Ganglia are collections of neuronal cell bodies in the peripheral nervous system and may be sensory or autonomic.'},'The old explanation incorrectly implied ganglia are exclusively autonomic.')
q=qs['IAE-1-SRC-0357'];pairs=json.loads(json.dumps(q['pairs']));pairs[3]={'premise':'Bulbar part of the spongy urethra.','target':'Traverses the bulb of the penis in the superficial perineal pouch.'}
add(357,{'pairs':pairs,'explanation':'The prostate is below the bladder neck and is traversed by prostatic urethra. Membranous urethra traverses the deep perineal region. The bulbar spongy urethra is in the superficial pouch, while its penile portion continues into the free penis. Seminal vesicles lie behind the bladder base.'},'The whole penile urethra is not confined to the superficial perineal pouch.')
ex(359,'Above the sacrum is spatially ambiguous, not a reliable false statement; the explanation invents a distinction between above S3 and above sacrum to defend the key.')
q=qs['IAE-1-SRC-0363'];pairs=json.loads(json.dumps(q['pairs']));pairs[-1]['premise']='Cavity of the body of the uterus.'
add(363,{'pairs':pairs},'The uterine body itself is pear-shaped; its cavity is triangular, as the explanation already states.')
add(372,{'explanation':'Each ejaculatory duct opens on the seminal colliculus in the posterior wall of the prostatic urethra, beside the prostatic utricle. Prostatic gland ducts, rather than ejaculatory ducts, open into the prostatic sinuses.'},'The previous explanation incorrectly locates the opening on the prostatic sinus.')
ex(376,'Rectum and uterus have substantial extraperitoneal/subperitoneal components. Describing uterus as enclosed in broad ligament and essentially intraperitoneal is misleading; the broad classification gives no clean unique alternative.')
add(377,{'text':'The anterior articular portion of the sacroiliac joint is classified as:'},'Sacroiliac joint has anterior synovial and posterior ligamentous components; specifies the intended synovial articulation.')
add(404,{'explanation':'The narrow lateral wall of the axilla is formed by the intertubercular sulcus of the humerus, with coracobrachialis and biceps related to it. Serratus anterior forms the medial wall; the pectoral muscles form the anterior wall; teres major contributes to the posterior wall.'},'The previous explanation wrongly says coracobrachialis and both biceps heads attach to the bicipital groove.')
add(422,{'text':'Which superficial vein at the elbow is commonly used for venepuncture?'},'Venepuncture is the intended application; intravenous injection has several valid peripheral sites.')
ex(430,'Common modern counting gives three palmar interossei and three thenar muscles, with adductor pollicis separate. Several groups have fewer than four; the historical four-palmar convention is unqualified.')
add(435,{'explanation':'The radial artery crosses the floor of the anatomical snuffbox. The cephalic vein and superficial radial nerve cross its roof, so it is misleading to call the artery its only content. Extensor pollicis longus forms the medial boundary.'},'The radial artery is not the only structure associated with the anatomical snuffbox.')
ex(453,'The fifth carpometacarpal joint can be described as a saddle-type articulation allowing opposition/cupping; the plane-only classification is convention-dependent alongside the clear ellipsoid wrist alternative.')
ex(455,'Wrist extensors have mixed radial-nerve supply: ECRL is radial, ECRB is usually deep radial, and ECU is posterior interosseous. The posterior-interosseous-only key is not reliably the main supply for wrist extension.')
add(457,{'text':'Which tendon passes within the capsule of the shoulder joint?'},'The intracapsular structure is the long-head biceps tendon, not its muscle belly.')
ex(498,'Femoral canal transmits femoral rather than inguinal hernia, and contains lymphatic vessels despite no vessels alternative. More than one statement is false.')
ex(505,'Gluteus medius is intermediate in depth (B), while hip abductors stabilize the pelvis in stance (D). The explanation rejects B by referring to minimus, which the option does not name.')
add(524,{'text':'Which listed intrinsic muscle has its belly on the dorsum of the foot?','explanation':'Extensor digitorum brevis is an intrinsic dorsal foot muscle. Extensor hallucis brevis is also present dorsally and is often described as its medial component. The other listed muscles have their bellies in the leg and reach the foot as tendons.'},'Calling EDB the only dorsal foot muscle ignores extensor hallucis brevis.')
add(529,{'text':'Deep to the flexor retinaculum at the ankle, which two structures lie immediately adjacent to the posterior tibial vessels on either side?'},'Several listed non-adjacent pairs also enclose the vessels; adjacent specifies the intended FDL/tibial nerve pair.')
add(549,{'text':'In the usual right-dominant coronary circulation, the posterior interventricular artery arises from ___.'},'Allows for left-dominant circumflex supply while preserving the intended right-coronary answer.')

def save(reviewed=550):
 (root/'decisions-IAE-1.jsonl').write_text(''.join(json.dumps(r,ensure_ascii=False)+'\n' for r in rows.values()))
 cov=[]
 for i,q in enumerate(ql):
  done=i<reviewed;cov.append({'module':'IAE-1','id':q['id'],'question_hash':hashlib.sha256(json.dumps(q,sort_keys=True,ensure_ascii=False).encode()).hexdigest(),'semantic_review_completed':done,'review_method':'Model self-review of displayed stem, options/pairs/blanks, key and explanation in bounded batches; selected opened evidence, not independent or full evidence adjudication.' if done else 'Not yet semantically reviewed; snapshot and structural inventory only.','evidence_verified':bool(rows.get(q['id'],{}).get('evidence')),'decision':rows.get(q['id'],{}).get('decision','no_change_proposed' if done else 'pending')})
 (root/'coverage-IAE-1.jsonl').write_text(''.join(json.dumps(r,ensure_ascii=False)+'\n' for r in cov))
if __name__=='__main__':save()
