import {z} from 'zod';
import {ReportError,type Identity} from './report-service.js';
import {bankEntries,questionVersion} from './question-bank.js';
import {editableQuestionSchema} from './question-edit-schema.js';
export interface QuestionEdit {moduleCode:string;chapterId:number;questionId:string;revision:number;baseVersion:string;question:any;updatedBy:string;updatedAt:string;subjectId?:string;deleted?:boolean}
export interface EditStore {list(moduleCode:string):Promise<QuestionEdit[]>;save(edit:Omit<QuestionEdit,'revision'>,revision:number):Promise<QuestionEdit>;history(moduleCode:string):Promise<QuestionEdit[]>}
const moduleCode=z.string().regex(/^[A-Z0-9]+(?:-[A-Z0-9]+)*-[1-5]$/);
const address={moduleCode,chapterId:z.number().int().nonnegative(),questionId:z.string().min(1).max(180),revision:z.number().int().nonnegative()};
const saveSchema=z.object({...address,question:editableQuestionSchema}).strict();
const createSchema=z.object({moduleCode,chapterId:address.chapterId,subjectId:z.string().min(1).max(100),question:editableQuestionSchema}).strict();
const removeSchema=z.object(address).strict();
function parse<T>(schema:z.ZodType<T>,body:unknown):T{const result=schema.safeParse(body);if(!result.success)throw new ReportError(400,result.error.issues[0]?.message??'Invalid question.');return result.data;}
export function createQuestionEditService(deps:{authenticate(token:string):Promise<Identity>;readBank(moduleCode:string):Promise<any>;store:EditStore}){
 async function owner(token:string){const user=await deps.authenticate(token);if(!user.isAdmin)throw new ReportError(403,'Only the owner can manage questions.');return user;}
 function target(bank:any,edit:QuestionEdit){return bank.chapters?.find((c:any)=>c.id===edit.chapterId)?.subjects?.find((s:any)=>s.id===edit.subjectId);}
 function eligible(bank:any,edit:QuestionEdit){const entries=bankEntries(bank);if(edit.baseVersion==='created')return Boolean(target(bank,edit))&&!entries.some((e:any)=>String(e.question.id)===edit.questionId);return entries.some((e:any)=>e.chapterId===edit.chapterId&&String(e.question.id)===edit.questionId&&questionVersion(e.question)===edit.baseVersion);}
 async function getEntry(code:string,chapter:number,id:string){const bank=await deps.readBank(code),edits=await deps.store.list(code);const entry=bankEntries(bank).find((e:any)=>e.chapterId===chapter&&String(e.question.id)===id);const edit=edits.find(e=>e.chapterId===chapter&&e.questionId===id);if(!entry&&!(edit?.baseVersion==='created'&&eligible(bank,edit)))throw new ReportError(404,'Question not found.');return {entry,edit,question:entry?.question??edit!.question};}
 return {
  async access(token:string){return owner(token);},
  async list(token:string,code:string){await owner(token);const bank=await deps.readBank(code),edits=await deps.store.list(code);const index=new Map(edits.map(e=>[`${e.chapterId}:${e.questionId}`,e]));const rows=bankEntries(bank).map((entry:any)=>{const edit=index.get(`${entry.chapterId}:${entry.question.id}`);const valid=edit&&eligible(bank,edit);return {...entry,revision:edit?.revision??0,question:valid?edit.question:entry.question,original:entry.question,deleted:Boolean(valid&&edit.deleted),staleOverride:Boolean(edit&&!valid)};});for(const edit of edits.filter(e=>e.baseVersion==='created'&&eligible(bank,e))){const chapter=bank.chapters.find((c:any)=>c.id===edit.chapterId),subject=target(bank,edit);rows.push({chapterId:edit.chapterId,chapterTitle:chapter.title,subjectId:edit.subjectId,subjectName:subject.name,revision:edit.revision,question:edit.question,original:null,deleted:Boolean(edit.deleted),staleOverride:false});}return rows;},
  async published(code:string){const bank=await deps.readBank(code),edits=await deps.store.list(code);return edits.filter(edit=>eligible(bank,edit)).map(edit=>({chapterId:edit.chapterId,questionId:edit.questionId,subjectId:edit.subjectId,baseVersion:edit.baseVersion,deleted:Boolean(edit.deleted),question:edit.question}));},
  async create(token:string,body:unknown){const user=await owner(token),input=parse(createSchema,body);if(input.question.lecture<1)throw new ReportError(400,'New questions need a positive lecture number.');const bank=await deps.readBank(input.moduleCode);const chapter=bank.chapters?.find((c:any)=>c.id===input.chapterId),subject=chapter?.subjects?.find((s:any)=>s.id===input.subjectId);if(!subject)throw new ReportError(400,'Choose an existing chapter and subject.');if(subject.lectureCount>0&&input.question.lecture>subject.lectureCount)throw new ReportError(400,'Choose a lecture within this subject.');const edits=await deps.store.list(input.moduleCode),id=String(input.question.id);if(bankEntries(bank).some((e:any)=>String(e.question.id)===id)||edits.some(e=>e.questionId===id))throw new ReportError(409,'This question ID already exists.');return deps.store.save({moduleCode:input.moduleCode,chapterId:input.chapterId,subjectId:input.subjectId,questionId:id,baseVersion:'created',question:input.question,deleted:false,updatedBy:user.id,updatedAt:new Date().toISOString()},0);},
  async save(token:string,body:unknown){const user=await owner(token),input=parse(saveSchema,body);const {entry,edit,question}=await getEntry(input.moduleCode,input.chapterId,input.questionId);if(String(input.question.id)!==input.questionId||input.question.lecture!==question.lecture)throw new ReportError(400,'Question ID and lecture routing cannot change.');if(JSON.stringify(input.question.subQuestions?.map((q:any)=>q.id)??[])!==JSON.stringify(question.subQuestions?.map((q:any)=>q.id)??[]))throw new ReportError(400,'Keep the original question-part IDs and order.');return deps.store.save({moduleCode:input.moduleCode,chapterId:input.chapterId,questionId:input.questionId,subjectId:entry?.subjectId??edit?.subjectId,baseVersion:entry?questionVersion(entry.question):'created',question:input.question,deleted:false,updatedBy:user.id,updatedAt:new Date().toISOString()},input.revision);},
  async remove(token:string,body:unknown){const user=await owner(token),input=parse(removeSchema,body);const {entry,edit,question}=await getEntry(input.moduleCode,input.chapterId,input.questionId);return deps.store.save({moduleCode:input.moduleCode,chapterId:input.chapterId,questionId:input.questionId,subjectId:entry?.subjectId??edit?.subjectId,baseVersion:entry?questionVersion(entry.question):'created',question:edit?.baseVersion==='created'||(entry&&edit?.baseVersion===questionVersion(entry.question))?edit!.question:question,deleted:true,updatedBy:user.id,updatedAt:new Date().toISOString()},input.revision);},
  async history(token:string,code:string){await owner(token);return deps.store.history(code);},
 };
}
