import {useEffect,useRef,useState} from 'react';
import {useAuth} from '@clerk/clerk-react';
import {useSearchParams} from 'react-router';
import {Search,Save,RotateCcw,History,Download,ChevronLeft,ChevronRight,BookOpen} from 'lucide-react';
import {questionBankRequest} from '../app/reports/client';
import {refreshQuestionCorrections} from '../app/data';
type Entry={chapterId:number;chapterTitle:string;subjectName:string;subjectId?:string;isNew?:boolean;deleted?:boolean;question:any;original:any;revision:number;staleOverride:boolean};
export default function AdminQuestionEditor(){
 const {getToken,userId}=useAuth(),token=useRef(getToken);token.current=getToken;
 const [params,setParams]=useSearchParams();
 const [modules,setModules]=useState<Array<{code:string;name:string;count:number}>>([]);
 const [moduleCode,setModule]=useState(params.get('module')??'MGL-3');
 const [search,setSearch]=useState(params.get('question')??''),[query,setQuery]=useState(search),[offset,setOffset]=useState(0);
 const [chapters,setChapters]=useState<any[]>([]);
 const [entries,setEntries]=useState<Entry[]>([]),[total,setTotal]=useState(0),[selected,setSelected]=useState<Entry|null>(null);
 const [draft,setDraft]=useState<any>(null),[json,setJSON]=useState(''),[advanced,setAdvanced]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[refresh,setRefresh]=useState(0),[history,setHistory]=useState<any[]|null>(null);
 useEffect(()=>{const abort=new AbortController();questionBankRequest<{modules:typeof modules}>(token.current,'?action=modules',{signal:abort.signal}).then(r=>{setModules(r.modules);if(!r.modules.some(m=>m.code===moduleCode)&&r.modules[0])setModule(r.modules[0].code);}).catch(e=>{if(!abort.signal.aborted)setError(e.message);});return()=>abort.abort();},[]);
 useEffect(()=>{const id=setTimeout(()=>{setQuery(search);setOffset(0);},250);return()=>clearTimeout(id);},[search]);
 useEffect(()=>{const abort=new AbortController();setLoading(true);setError('');questionBankRequest<{questions:Entry[];total:number;chapters?:any[]}>(token.current,`?moduleCode=${encodeURIComponent(moduleCode)}&search=${encodeURIComponent(query)}&offset=${offset}`,{signal:abort.signal}).then(r=>{if(!abort.signal.aborted){setEntries(r.questions);setTotal(r.total);setChapters(r.chapters??[]);}}).catch(e=>{if(!abort.signal.aborted)setError(e.message);}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[moduleCode,query,offset,refresh]);
 const draftKey=(entry:Entry)=>`asu_admin_draft:${userId}:${moduleCode}:${entry.chapterId}:${entry.question.id}`;
 const dirty=Boolean(selected && (advanced ? json!==JSON.stringify(selected.question,null,2) : JSON.stringify(draft)!==JSON.stringify(selected.question)));
 useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 useEffect(()=>{
  if(!userId||!selected)return;
  try {
   if(dirty)localStorage.setItem(draftKey(selected),JSON.stringify({revision:selected.revision,advanced,draft,json}));
   else localStorage.removeItem(draftKey(selected));
  } catch { /* The unload warning remains available if device storage is full. */ }
 },[dirty,draft,json,advanced,selected,userId,moduleCode]);
 function open(entry:Entry){
  if(dirty&&!window.confirm('Discard unsaved question changes?'))return;
  if(dirty&&selected&&userId)localStorage.removeItem(draftKey(selected));
  let saved:any=null;
  try {if(userId)saved=JSON.parse(localStorage.getItem(draftKey(entry))??'null');}catch{}
  const restore=saved&&saved.revision===entry.revision&&window.confirm('Restore your unsaved draft from this device?');
  setSelected(entry);setDraft(restore?saved.draft:structuredClone(entry.question));setJSON(restore?saved.json:JSON.stringify(entry.question,null,2));setAdvanced(restore?saved.advanced:false);setHistory(null);setMessage(restore?'Your unsaved draft was restored. Review before publishing.':'');setError('');setParams({module:moduleCode,question:String(entry.question.id)});
 }
 function field(key:string,value:any){if(advanced){try{const q={...JSON.parse(json),[key]:value};setDraft(q);setJSON(JSON.stringify(q,null,2));}catch{setError('Fix the JSON before changing routing.');return;}}else setDraft((q:any)=>({...q,[key]:value}));setMessage('');}
 async function save(){if(!selected||busy)return;setBusy(true);setError('');setMessage('');try{const question=advanced?JSON.parse(json):draft;const body=selected.isNew?{moduleCode,chapterId:selected.chapterId,subjectId:selected.subjectId,question}:{moduleCode,chapterId:selected.chapterId,questionId:String(selected.question.id),revision:selected.revision,question};const {edit}=await questionBankRequest<{edit:any}>(token.current,'',{method:selected.isNew?'POST':'PATCH',body:JSON.stringify(body)});const updated={...selected,isNew:false,deleted:false,question:edit.question,revision:edit.revision,staleOverride:false};setSelected(updated);setDraft(structuredClone(edit.question));setJSON(JSON.stringify(edit.question,null,2));setHistory(null);setRefresh(x=>x+1);await refreshQuestionCorrections();setMessage('Correction published to the question bank. Existing attempts keep their original question snapshot.');}catch(e){setError(e instanceof Error?e.message:'Unable to save.');}finally{setBusy(false);}}
 function newQuestion(){
  const chapter=chapters.find(c=>c.subjects?.length);if(!chapter){setError('This module has no chapter/subject routing available.');return;}
  const subject=chapter.subjects[0],question={id:`ADMIN-${crypto.randomUUID()}`,type:'mcq',lecture:1,text:'',options:['',''],correctIndex:0,explanation:''};
  open({chapterId:chapter.id,chapterTitle:chapter.title,subjectId:subject.id,subjectName:subject.name,question,original:null,revision:0,staleOverride:false,isNew:true});
 }
 async function removeQuestion(){if(!selected||busy||!window.confirm('Remove this question from student practice? You can restore it here.'))return;setBusy(true);setError('');try{const {edit}=await questionBankRequest<{edit:any}>(token.current,'',{method:'DELETE',body:JSON.stringify({moduleCode,chapterId:selected.chapterId,questionId:String(selected.question.id),revision:selected.revision})});setSelected({...selected,question:edit.question,revision:edit.revision,deleted:true});setDraft(structuredClone(edit.question));setJSON(JSON.stringify(edit.question,null,2));setRefresh(x=>x+1);setHistory(null);await refreshQuestionCorrections();setMessage('Question removed from student practice. Its history is retained; publish to restore it.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function changeType(type:string){const common={id:draft.id,text:draft.text,lecture:draft.lecture,explanation:draft.explanation};const extras=type==='essay'?{modelAnswer:''}:type==='fillblank'?{blanks:[''],acceptedAnswers:[['']]}:type==='matching'?{pairs:[{premise:'',target:''}]}:type==='case'?{subQuestions:[{id:crypto.randomUUID(),type:'essay',text:'',modelAnswer:'',explanation:''}]}:{options:type==='truefalse'?['True','False']:['',''],correctIndex:0};const value={...common,type,...extras};setDraft(value);setJSON(JSON.stringify(value,null,2));setAdvanced(['case','matching','fillblank'].includes(type));}
 async function loadHistory(){try{const r=await questionBankRequest<{history:any[]}>(token.current,`?action=history&moduleCode=${moduleCode}`);setHistory(r.history.filter(h=>h.chapterId===selected?.chapterId&&h.questionId===String(selected?.question.id)));}catch(e){setError((e as Error).message);}}
 async function exportEdits(){try{const r=await questionBankRequest(token.current,`?action=history&moduleCode=${moduleCode}`);const url=URL.createObjectURL(new Blob([JSON.stringify(r,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`${moduleCode}-question-revisions.json`;a.click();URL.revokeObjectURL(url);}catch(e){setError((e as Error).message);}}
 return <section>
  <header className="admin-topline"><div><h1 className="admin-title">Question studio</h1><p className="report-muted">Find, preview, and correct your question bank. Every save keeps a revision.</p></div><div className="admin-actions"><button className="report-primary" onClick={newQuestion} disabled={loading||busy}>Add question</button><button className="report-secondary" onClick={exportEdits}><Download size={15}/>Export revisions</button></div></header>
  <div className="admin-surface mb-5 flex flex-wrap gap-4 p-5"><label className="report-field flex-1">Module<select value={moduleCode} onChange={e=>{if(dirty&&!window.confirm('Discard unsaved question changes?'))return;if(dirty&&selected&&userId)localStorage.removeItem(draftKey(selected));setModule(e.target.value);setSelected(null);setDraft(null);setHistory(null);setSearch('');setOffset(0);setParams({module:e.target.value});}}>{modules.map(m=><option key={m.code} value={m.code}>{m.code} · {m.name} ({m.count.toLocaleString()} source)</option>)}</select></label><label className="report-field flex-1">Search questions<div className="flex items-center gap-2"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Question text, ID, subject, or chapter"/></div></label></div>
  {error&&<p role="alert" className="report-error mb-4">{error}</p>}{message&&<p role="status" className="admin-surface mb-4 p-4 text-physiology">{message}</p>}
  <div className="grid gap-5 xl:grid-cols-[minmax(250px,1fr)_minmax(0,2fr)]">
   <section className="admin-surface p-4"><p className="report-muted mb-4">{total.toLocaleString()} questions</p>{loading?<p role="status">Loading questions…</p>:entries.length===0?<p>No matching questions.</p>:entries.map(entry=><button key={`${entry.chapterId}:${entry.question.id}`} onClick={()=>open(entry)} className={`mb-2 block w-full rounded-2xl border p-4 text-start transition-all hover:border-physiology/40 active:scale-[.99] ${selected?.question.id===entry.question.id?'border-physiology/40 bg-physiology/5':'border-border bg-secondary/20'}`}><span className="block text-xs text-muted-foreground">{entry.subjectName} · {entry.chapterTitle}</span><span className="mt-2 block line-clamp-3 text-sm font-semibold">{entry.question.text}</span><span className="mt-2 block text-xs text-muted-foreground">{entry.deleted?'Removed · ':''}{entry.question.type} · Revision {entry.revision}</span></button>)}<div className="admin-actions mt-4"><button className="report-secondary" disabled={offset===0||loading} onClick={()=>setOffset(Math.max(0,offset-25))}><ChevronLeft size={15}/>Previous</button><button className="report-secondary" disabled={offset+25>=total||loading} onClick={()=>setOffset(offset+25)}>Next<ChevronRight size={15}/></button></div></section>
   {selected&&draft?<section className="admin-surface p-5 sm:p-7"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><p className="admin-meta">{selected.question.id}</p><h2 className="text-lg font-bold">{selected.subjectName} · {selected.question.type}</h2></div><button className="report-secondary" onClick={()=>{if(!advanced)setJSON(JSON.stringify(draft,null,2));else{try{setDraft(JSON.parse(json));}catch{setError('Fix the JSON before switching views.');return;}}setAdvanced(!advanced);}}>{advanced?'Form editor':'Full format editor'}</button></div>
    {selected.isNew&&<div className="mb-5 space-y-4"><label className="report-field">Destination chapter and subject<select value={`${selected.chapterId}:${selected.subjectId}`} onChange={e=>{const [id,subjectId]=e.target.value.split(':');const chapter=chapters.find(c=>c.id===Number(id)),subject=chapter.subjects.find((s:any)=>s.id===subjectId);setSelected({...selected,chapterId:chapter.id,chapterTitle:chapter.title,subjectId,subjectName:subject.name});field('lecture',1);}}>{chapters.flatMap(c=>c.subjects.map((s:any)=><option key={`${c.id}:${s.id}`} value={`${c.id}:${s.id}`}>{c.title} · {s.name}</option>))}</select></label><label className="report-field">Question type<select value={draft.type} onChange={e=>changeType(e.target.value)}>{['mcq','truefalse','essay','fillblank','matching','case'].map(type=><option key={type} value={type}>{type}</option>)}</select></label><label className="report-field">Lecture / topic{chapters.find(c=>c.id===selected.chapterId)?.subjects.find((s:any)=>s.id===selected.subjectId)?.lectureNames?.length ? <select value={draft.lecture} onChange={e=>field('lecture',Number(e.target.value))}>{chapters.find(c=>c.id===selected.chapterId).subjects.find((s:any)=>s.id===selected.subjectId).lectureNames.map((name:string,i:number)=><option key={i} value={i+1}>{i+1} · {name}</option>)}</select> : <input type="number" min={1} value={draft.lecture} onChange={e=>field('lecture',Number(e.target.value))}/>}</label></div>}
    {selected.deleted&&<p role="status" className="report-muted mb-4">Removed from student practice. Publish this question to restore it.</p>}
    {selected.staleOverride&&<p role="alert" className="report-error mb-4">The source bank changed after its last correction. Review this current source question before saving a new revision.</p>}
    {advanced?<label className="report-field">Complete question JSON<textarea rows={24} className="font-mono text-xs" value={json} onChange={e=>setJSON(e.target.value)} disabled={busy}/></label>:<div className="space-y-4"><label className="report-field">Question prompt<textarea rows={5} value={draft.text} onChange={e=>field('text',e.target.value)} disabled={busy}/></label>
      {['mcq','truefalse'].includes(draft.type)&&<fieldset><legend className="text-sm font-semibold mb-3">Options and correct answer</legend>{draft.options?.map((option:string,i:number)=><label key={i} className="mb-2 flex items-center gap-3"><input type="radio" name="correct-option" aria-label={`Correct answer ${i+1}`} checked={draft.correctIndex===i} onChange={()=>field('correctIndex',i)} disabled={busy}/><input className="w-full rounded-xl border border-border bg-secondary/30 p-3" aria-label={`Option ${i+1}`} value={option} onChange={e=>field('options',draft.options.map((o:string,j:number)=>j===i?e.target.value:o))} disabled={busy}/></label>)}</fieldset>}
      {draft.type==='essay'&&<label className="report-field">Model answer<textarea rows={8} value={draft.modelAnswer??''} onChange={e=>field('modelAnswer',e.target.value)} disabled={busy}/></label>}
      {['case','casestudy','matching','fillblank'].includes(draft.type)&&<p className="report-muted">Use the full format editor to edit question parts, matching pairs, blank answers, and accepted variants.</p>}
      <label className="report-field">Explanation<textarea rows={5} value={draft.explanation??''} onChange={e=>field('explanation',e.target.value)} disabled={busy}/></label>
    </div>}
    {dirty&&<p className="report-muted mt-5">Unsaved changes. Signed-in drafts are kept on this device when you leave the studio.</p>}<div className="admin-actions mt-6"><button className="report-primary" onClick={save} disabled={busy}><Save size={15}/>{busy?'Saving…':selected.isNew?'Publish new question':selected.deleted?'Restore question':'Publish correction'}</button><button className="report-secondary" onClick={()=>{if(selected.original&&window.confirm('Load the original source version into the editor? Review and publish to restore it.')){setDraft(structuredClone(selected.original));setJSON(JSON.stringify(selected.original,null,2));setMessage('Original source loaded as an unsaved draft.');}}} disabled={busy||!selected.original}><RotateCcw size={15}/>Restore source draft</button>{!selected.isNew&&!selected.deleted&&<button className="report-secondary" onClick={removeQuestion} disabled={busy}>Remove question</button>}<button className="report-secondary" onClick={loadHistory} disabled={selected.isNew}><History size={15}/>Revisions</button></div>
    {history&&<section className="mt-6 border-t border-border pt-5"><h3 className="font-semibold mb-3">Revision history</h3>{history.length===0?<p className="report-muted">No corrections yet.</p>:history.map(edit=><div key={edit.revision} className="mb-3 rounded-xl bg-secondary/30 p-3 text-sm"><p>Revision {edit.revision} · {new Date(edit.updatedAt).toLocaleString()}</p><button className="mt-2 underline" onClick={()=>{setDraft(structuredClone(edit.question));setJSON(JSON.stringify(edit.question,null,2));setMessage(`Revision ${edit.revision} loaded as an unsaved draft.`);}}>Load this revision</button></div>)}</section>}
   </section>:<section className="admin-surface admin-empty"><BookOpen size={30} className="mx-auto mb-4 text-physiology"/><h2 className="font-semibold">Choose a question to begin</h2><p className="report-muted">Your changes are validated and saved with a revision history.</p></section>}
  </div>
 </section>;
}
