import {useEffect,useRef,useState} from 'react';
import {useAuth} from '@clerk/clerk-react';
import {reportRequest} from '../app/reports/client';
import type {TriageAssessment,TriageView} from '../app/reports/triage-contracts';
import {StudyButton,StatusMessage} from '../app/components/ui/StudyControls';
export function TriagePanel({refresh,onRefresh,onData}:{refresh:number;onRefresh:()=>void;onData?:(view:TriageView)=>void}){
 const {getToken}=useAuth(),token=useRef(getToken);token.current=getToken;
 const [data,setData]=useState<TriageView|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[running,setRunning]=useState(false);
 const queue=useRef(false);useEffect(()=>()=>{queue.current=false;},[]);
 useEffect(()=>{const controller=new AbortController();reportRequest<TriageView>(token.current,'?action=triage',{signal:controller.signal}).then(v=>{if(!v?.metrics||!v?.counts||!Array.isArray(v.assessments))throw new Error('AI triage is unavailable. Original reports remain accessible.');if(!controller.signal.aborted){setData(v);onData?.(v);setError('');}}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[refresh]);
 async function action(name:string,body:unknown){setBusy(true);setError('');try{const value=await reportRequest<{reason?:string}>(token.current,`?action=triage-${name}`,{method:'POST',body:JSON.stringify(body),signal:AbortSignal.timeout(65000)});setMessage(value.reason??'Triage updated. Original reports are unchanged.');onRefresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function runQueue(){queue.current=true;setRunning(true);setBusy(true);setError('');try{for(let i=0;i<20&&queue.current;i++){const value=await reportRequest<{processed:boolean;reason?:string;assessment?:TriageAssessment}>(token.current,'?action=triage-run',{method:'POST',body:'{}',signal:AbortSignal.timeout(65000)});onRefresh();if(!value.processed||value.assessment?.state==='unreviewed'){setMessage(value.reason??'Review paused after a provider/evidence failure. Retry timing is preserved.');break;}}}catch(e){setError((e as Error).message);}finally{queue.current=false;setRunning(false);setBusy(false);}}
 return <section className="admin-surface triage-panel" aria-labelledby="triage-title"><header><div><p className="triage-eyebrow">Assisted review</p><h2 id="triage-title">Your inbox, with context.</h2><p className="report-muted">AI suggests priorities. You decide every correction.</p></div><span className="admin-badge">{data?.mode==='prioritized'?'Prioritized inbox':'Shadow mode'}</span></header>
 {error&&<StatusMessage kind="error">{error}</StatusMessage>}
 {data?<><div className="triage-stats"><div><strong>{data.counts.decision}</strong><span>Needs a decision</span></div><div><strong>{data.counts.uncertain}</strong><span>Uncertain / unreviewed</span></div><div><strong>{data.counts.low}</strong><span>Low priority</span></div><div><strong>{data.metrics.labelled} / 50</strong><span>Owner-labelled pilot</span></div></div>
 <p className="report-muted">{data.mode==='shadow'?'Every report remains visible while we evaluate the AI.':'Low-priority reports are in the separate view; All reports always preserves the full inbox.'} {data.pending} groups await review. No question is changed automatically.</p>
 <details className="triage-explainer"><summary>Quality gate and usage budget</summary><p>Enable prioritization after at least 50 current labelled groups, including 10 actionable cases, with no incorrect low-priority placements. Self-reported confidence is not proof. Medical conclusions need fetched supporting evidence.</p><p>{data.metrics.actionable} actionable labels · {data.metrics.falseLow} false low-priority placements · {data.metrics.criticalMisses} critical misses.</p><p>At most {data.config.dailyLimit} provider calls per Cairo day, one group at a time. Tutor quota gets priority. Provider failures remain unreviewed; repeats share the same assessment.</p>{!data.config.provider&&<p>AI review needs the existing GROQ_API_KEY on the server. No key is stored in the browser.</p>}</details>
 <div className="admin-actions"><StudyButton variant="secondary" disabled={!running&&(busy||!data.config.provider)} onClick={()=>{if(running){queue.current=false;setMessage('Stopping after the current group is saved.');}else void runQueue();}}>{running?'Stop queue':'Review queued groups'}</StudyButton><StudyButton disabled={busy||!data.config.provider} busy={busy} onClick={()=>action('run',{})}>Review next group</StudyButton><StudyButton variant="secondary" disabled={busy||!data.metrics.ready} onClick={()=>action('mode',{mode:'prioritized'})}>Enable prioritization</StudyButton>{data.mode==='prioritized'&&<StudyButton variant="secondary" disabled={busy} onClick={()=>action('mode',{mode:'shadow'})}>Return to shadow mode</StudyButton>}</div>
 </>:!error&&<p role="status">Loading triage status…</p>}{message&&<StatusMessage>{message}</StatusMessage>}</section>;
}
export function TriageAssessmentCard({assessment,onRefresh}:{assessment?:TriageAssessment;onRefresh:()=>void}){
 const {getToken}=useAuth(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[label,setLabel]=useState('actionable'),[notes,setNotes]=useState(''),[critical,setCritical]=useState(false),[message,setMessage]=useState('');
 async function action(name:string,body:unknown){setBusy(true);setError('');try{await reportRequest(getToken,`?action=triage-${name}`,{method:'POST',body:JSON.stringify(body)});setMessage('Saved. The original report is unchanged.');onRefresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(!assessment)return <section className="triage-assessment"><h3>AI review</h3><p className="report-muted">Unreviewed. This report remains in your inbox until it can be assessed.</p></section>;
 return <section className="triage-assessment"><h3>AI review · {assessment.priority==='decision'?'Needs your decision':assessment.priority==='low'?'Low priority':'Uncertain'}</h3><p className="admin-meta">{assessment.state} · {new Date(assessment.checkedAt).toLocaleString()} · {assessment.version}</p><p>{assessment.rationale}</p><p><strong>Suggested action:</strong> {assessment.action}</p>{assessment.independentAnswer!==null&&<p>Uncued review selected option {String.fromCharCode(65+assessment.independentAnswer)}. This is a suggestion, not an approved correction.</p>}
 {assessment.citations.map((c,i)=>{const source=assessment.evidence.find(s=>s.id===c.sourceId);return source&&<blockquote key={i}><p>{c.claim}</p><p>“{c.quote}”</p><a href={source.url} target="_blank" rel="noopener noreferrer">{source.title}</a><small>Retrieved {new Date(source.retrievedAt).toLocaleDateString()}</small></blockquote>;})}
 <details><summary>Review provenance</summary><p>Models: {assessment.models.join(', ')||'Deterministic checks only'}.</p><p className="triage-version">Question version: {assessment.sourceVersion}</p><p>Fetched quotes establish source provenance; the AI's interpretation still requires your judgement.</p>{assessment.retryAt&&<p>Retry after {new Date(assessment.retryAt).toLocaleString()}.</p>}</details>
 <StudyButton variant="secondary" disabled={busy} onClick={()=>action('reassess',{key:assessment.key})}>Request reassessment</StudyButton>
 {assessment.state==='complete'&&<details><summary>Label this review / disagree with AI</summary><label className="report-field">Your judgement<select value={label} onChange={e=>setLabel(e.target.value)}><option value="actionable">Actionable error</option><option value="uncertain">Uncertain</option><option value="low">Low priority / no defect found</option></select></label><label className="triage-check"><input type="checkbox" checked={critical} onChange={e=>setCritical(e.target.checked)}/>Critical medical/key error</label><label className="report-field">Decision rationale<textarea value={notes} onChange={e=>setNotes(e.target.value)} maxLength={2000}/></label><StudyButton disabled={busy||!notes.trim()} onClick={()=>action('label',{key:assessment.key,fingerprint:assessment.fingerprint,label,critical,notes:notes.trim()})}>Save owner judgement</StudyButton><p className="admin-meta">This labels the pilot, not the report status. Apply corrections through Question studio and confirm them yourself.</p></details>}
 {error&&<StatusMessage kind="error">{error}</StatusMessage>}{message&&<StatusMessage>{message}</StatusMessage>}</section>;
}
