import {describe,it,expect} from 'vitest';
import { groupForTriage, aiSource, assessStructure, finalPriority, validateCitations, pilotMetrics } from '../../../server/report-triage.js';
import type {QuestionReport} from '../../app/reports/contracts';
const report=(patch:Partial<QuestionReport>={}):QuestionReport=>({id:'r_a',requestHash:'hash',reporterId:'user_secret',reporter:{name:'Sara Ali',username:'sara',email:'sara@asu.test',emailVerified:true},category:'wrong_answer',explanation:'Sara Ali user_secret sara@asu.test says the answer is wrong',snapshot:{moduleCode:'MGL-3',chapterId:1,chapterTitle:'One',subjectName:'Anatomy',version:'v1',question:{id:'Q1',type:'mcq',text:'Which nerve?',options:['IX','X'],correctIndex:0}},status:'new',notes:'',revision:1,createdAt:'2026-10-09',updatedAt:'2026-10-09',notification:{state:'pending'},...patch});
describe('Conservative report triage',()=>{
 it('groups exact issues without combining changed versions or child parts and deduplicates repeated records',()=>{const a=report(),b=report({id:'r_b',reporterId:'other'}),c=report({id:'r_c',snapshot:{...a.snapshot,version:'v2'}});const g=groupForTriage([a,a,b,c]);expect(g).toHaveLength(2);expect(g[0].reports).toHaveLength(2);expect(g[0].reporters).toBe(2);expect(groupForTriage([a,{...a,id:'r_d',subQuestionId:'SQ1'}])).toHaveLength(2);});
 it('keeps identity and key out of blind review and scrubs known private data from notes',()=>{const s=JSON.stringify(aiSource(groupForTriage([report()])[0],true));for(const value of ['Sara Ali','user_secret','sara@asu.test','correctIndex','explanation'])expect(s).not.toContain(value);const c=JSON.stringify(aiSource(groupForTriage([report()])[0],false));expect(c).not.toContain('Sara Ali');expect(c).not.toContain('user_secret');expect(c).not.toContain('sara@asu.test');});
 it('detects missing keys, duplicate options and blank prompts without modifying originals',()=>{const r=report();const before=JSON.stringify(r);expect(assessStructure(r.snapshot.question)).toEqual([]);expect(assessStructure({...r.snapshot.question,correctIndex:9,options:['same',' same '],text:''}).length).toBeGreaterThanOrEqual(3);expect(JSON.stringify(r)).toBe(before);});
 it('never puts critical ambiguity, changed content, malformed key or unsupported medical assessments in low priority',()=>{expect(finalPriority({issue:'multiple_answers',priority:'low',medical:true,unique:false,supported:true,stale:false,structural:[]})).toBe('decision');expect(finalPriority({issue:'wrong_key',priority:'low',medical:true,unique:true,supported:false,stale:false,structural:[]})).toBe('uncertain');expect(finalPriority({issue:'formatting',priority:'low',medical:false,unique:true,supported:true,stale:true,structural:[]})).toBe('uncertain');});
 it('accepts only exact quotes from actually retrieved evidence and rejects invented source IDs',()=>{const sources=[{id:'s1',url:'https://pubmed.ncbi.nlm.nih.gov/123/',title:'Study',text:'The glossopharyngeal nerve supplies the stylopharyngeus muscle.',retrievedAt:'now'}];expect(validateCitations([{sourceId:'s1',quote:sources[0].text,claim:'muscle innervation'}],sources)).toHaveLength(1);expect(validateCitations([{sourceId:'s9',quote:sources[0].text,claim:'x'},{sourceId:'s1',quote:'not in the paper',claim:'x'}],sources)).toHaveLength(0);});
 it('requires a real pilot and rejects a critical error hidden as low priority',()=>{expect(pilotMetrics([]).ready).toBe(false);const rows=Array.from({length:50},(_,i)=>({key:String(i),label:i<10?'actionable':'low',priority:i<10?'decision':'low',critical:i<10}));expect(pilotMetrics(rows).ready).toBe(true);rows[0].priority='low';expect(pilotMetrics(rows).ready).toBe(false);});
});

it('retains the clinical parent stem in uncued child review while excluding its answer',()=>{const r=report();r.subQuestionId='SQ1';r.snapshot.question={id:'CASE',type:'case',text:'Tongue deviates to the right after injury.',modelAnswer:'Hidden answer',subQuestions:[{id:'SQ1',type:'mcq',text:'Which side?',options:['Right','Left'],correctIndex:0}]};const input=JSON.stringify(aiSource(groupForTriage([r])[0],true));expect(input).toContain('Tongue deviates');expect(input).toContain('Which side?');expect(input).not.toContain('Hidden answer');expect(input).not.toContain('correctIndex');});
