import {it,expect,vi} from 'vitest';
import {reviewGroup,createTriageService} from '../../../server/triage-worker';
import {groupForTriage} from '../../../server/report-triage';
import {fetchEvidence} from '../../../server/triage-evidence';
import type {QuestionReport} from '../../app/reports/contracts';
const r:QuestionReport={id:'r_'+'a'.repeat(40),requestHash:'x',reporterId:'secret',category:'wrong_answer',explanation:'wrong key',status:'new',notes:'',revision:1,createdAt:'now',updatedAt:'now',notification:{state:'pending'},snapshot:{moduleCode:'MGL-3',chapterId:1,chapterTitle:'x',subjectName:'y',version:'v1',question:{id:'Q',type:'mcq',text:'Which nerve?',options:['IX','X'],correctIndex:0}}};
const group=()=>groupForTriage([r])[0];
const classify={issue:'wrong_key',priority:'low',rationale:'Check it',action:'Review key',medical:true};
it('blind solve happens before key comparison and unsupported conclusions cannot be dismissed',async()=>{const calls:any[]=[];const model=vi.fn(async(phase:string,input:unknown)=>{calls.push([phase,input]);return phase==='classify'?classify:phase==='blind'?{answerIndex:0,unique:true,optionReasons:['supplies muscle','another role'],rationale:'IX',queries:['stylopharyngeus innervation']}:{supported:false,citations:[]};});const a=await reviewGroup(group(),{model,evidence:async()=>[],now:()=>new Date('2026-10-09'),current:async()=>r.snapshot});expect(a.priority).toBe('uncertain');expect(calls[1][0]).toBe('blind');expect(JSON.stringify(calls[1][1])).not.toContain('correctIndex');expect(JSON.stringify(calls[1][1])).not.toContain('wrong key');});
it('stale source is retained as uncertain without provider work',async()=>{const model=vi.fn();const a=await reviewGroup(group(),{model,evidence:async()=>[],current:async()=>({...r.snapshot,version:'v2'})});expect(a.state).toBe('stale');expect(model).not.toHaveBeenCalled();});
it('provider failure remains unreviewed with retry timing and never changes reports',async()=>{const original=JSON.stringify(r);const model=vi.fn(async()=>{throw Object.assign(new Error('quota'),{retrySeconds:120});});const a=await reviewGroup(group(),{model,evidence:async()=>[],current:async()=>r.snapshot,now:()=>new Date('2026-10-09T00:00:00Z')});expect(a.state).toBe('unreviewed');expect(a.retryAt).toBe('2026-10-09T00:02:00.000Z');expect(JSON.stringify(r)).toBe(original);});
it('structural errors skip paid/provider work',async()=>{const bad={...r,snapshot:{...r.snapshot,question:{...r.snapshot.question,correctIndex:9}}};const model=vi.fn();const a=await reviewGroup(groupForTriage([bad])[0],{model,evidence:async()=>[],current:async()=>bad.snapshot});expect(a.priority).toBe('decision');expect(model).not.toHaveBeenCalled();});
it('a fabricated citation cannot validate a medical dismissal',async()=>{const model=vi.fn(async(p:string)=>p==='classify'?classify:p==='blind'?{answerIndex:0,unique:true,optionReasons:['x','y'],rationale:'x',queries:['nerve']}:{supported:true,citations:[{sourceId:'fake',quote:'The evidence proves that this answer is correct.',claim:'key'}]});const a=await reviewGroup(group(),{model,evidence:async()=>[{id:'s1',url:'https://pubmed.ncbi.nlm.nih.gov/1/',title:'x',text:'Different facts',retrievedAt:'now'}],current:async()=>r.snapshot});expect(a.priority).toBe('uncertain');});
it('authorizes before reading private reports or sidecars',async()=>{const records=vi.fn(),store:any={};const svc=createTriageService({owner:async()=>{throw new Error('denied');},records,store,review:vi.fn()});await expect(svc.view('student')).rejects.toThrow('denied');expect(records).not.toHaveBeenCalled();});
it('NCBI retrieval rejects redirects and does not fetch arbitrary model URLs',async()=>{const fetcher=vi.fn(async(_url:RequestInfo|URL)=>new Response('',{status:302,headers:{location:'http://127.0.0.1/secrets'}}));expect(await fetchEvidence(['https://evil.test/x'],fetcher)).toEqual([]);expect(fetcher.mock.calls.every(([u])=>String(u).startsWith('https://eutils.ncbi.nlm.nih.gov/'))).toBe(true);});
function memoryStore(){let held=false,mode:'shadow'|'prioritized'='shadow';const values:Record<string,any>={},labels:any[]=[];return {values,async read(keys:string[]){return Object.fromEntries(keys.filter(k=>values[k]).map(k=>[k,values[k]]));},async save(a:any,_lease:string){values[a.fingerprint]=structuredClone(a);return true;},async lease(){if(held)return null;held=true;return 'lease';},async release(){held=false;},async reserve(){return true;},async labels(){return labels;},async label(l:any){labels.push(l);},async mode(v?:'shadow'|'prioritized'){if(v)mode=v;return mode;}};}
it('runs one group idempotently and releases the lease; malformed/failed work is retained',async()=>{const store=memoryStore(),review=vi.fn(async(g:any)=>reviewGroup(g,{model:async()=>{throw new Error('offline');},evidence:async()=>[],current:async()=>r.snapshot}));const svc=createTriageService({owner:async()=>({id:'owner'}),records:async()=>[r,r],store,review});expect((await svc.run('token')).processed).toBe(true);expect((await svc.run('token')).processed).toBe(false);expect(review).toHaveBeenCalledTimes(1);expect((await svc.view('token')).pending).toBe(1);await svc.reassess('token',group().key);expect((await svc.run('token')).processed).toBe(true);});
it('cannot activate without current pilot labels and cannot label stale evidence',async()=>{const store=memoryStore();const svc=createTriageService({owner:async()=>({id:'owner'}),records:async()=>[r],store,review:vi.fn()});await expect(svc.mode('token','prioritized')).rejects.toMatchObject({status:409});await expect(svc.label('token',{key:group().key,fingerprint:group().fingerprint,label:'low',critical:false,notes:'Reviewed'})).rejects.toMatchObject({status:409});});
it('revalidates low assessments when the owner changed the question',async()=>{const store=memoryStore(),g=group();store.values[g.fingerprint]={key:g.key,fingerprint:g.fingerprint,state:'complete',priority:'low',sourceVersion:'v1'};const svc=createTriageService({owner:async()=>({id:'owner'}),records:async()=>[r],store,review:vi.fn(),current:async()=>({...r.snapshot,version:'v2'})});const view=await svc.view('token');expect(view.assessments[0].state).toBe('stale');expect(view.lowReportIds).toEqual([]);});
it('retrieves bounded PubMed abstracts with exact provenance',async()=>{const fetcher=vi.fn(async(u:RequestInfo|URL)=>String(u).includes('esearch')?new Response(JSON.stringify({esearchresult:{idlist:['123']}})):new Response('<PubmedArticle><PMID Version="1">123</PMID><ArticleTitle>Anatomy evidence</ArticleTitle><AbstractText>The glossopharyngeal nerve supplies the stylopharyngeus muscle, which elevates the pharynx.</AbstractText></PubmedArticle>'));const sources=await fetchEvidence(['stylopharyngeus innervation'],fetcher);expect(sources).toHaveLength(1);expect(sources[0].url).toBe('https://pubmed.ncbi.nlm.nih.gov/123/');expect(sources[0].text).toContain('glossopharyngeal');});

it('evidence review receives the reported explanation after uncued derivation',async()=>{const bad={...r,category:'other' as const,snapshot:{...r.snapshot,question:{...r.snapshot.question,explanation:'A false explanation needs checking.'}}};let evidenceInput:any,blindInput:any;const model=vi.fn(async(p:string,input:any)=>{if(p==='classify')return {...classify,issue:'explanation'};if(p==='blind'){blindInput=input;return {answerIndex:0,unique:true,optionReasons:['x','y'],rationale:'x',queries:['nerve']};}evidenceInput=input;return {supported:false,citations:[]};});const a=await reviewGroup(groupForTriage([bad])[0],{model,evidence:async()=>[{id:'1',url:'https://pubmed.ncbi.nlm.nih.gov/1/',title:'Evidence',text:'The nerve supplies this muscle according to the anatomy study.',retrievedAt:'now'}],current:async()=>bad.snapshot});expect(model).toHaveBeenCalledTimes(3);expect(JSON.stringify(blindInput)).not.toContain('false explanation');expect(JSON.stringify(evidenceInput)).toContain('A false explanation needs checking.');expect(evidenceInput.concern.issue).toBe('explanation');expect(a.state).toBe('complete');expect(a.priority).toBe('uncertain');});
